#!/bin/sh -ex

BAKECONF_PARAMS=$1
git reset
git remote add origin-kernel git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git || echo "ignore"
git fetch origin-kernel
git config --global user.email "you@example.com"
git config --global user.name "temp"
git commit -a -m "temp patch if any" || echo "ignore"
git merge origin-kernel/master
#git rebase origin-kernel/master
make clean ARCH=sim
make defconfig ARCH=sim
make library ARCH=sim COV=yes
cd arch/sim/test

make bake
cd bake
hg pull -u
cd ..
rm -rf buildtop
make testbin $(BAKECONF_PARAMS)
cd ../../../
rm -rf arch/sim/test/buildtop/source/ns-3-dce/testpy-output
make test ARCH=sim ADD_PARAM="-r"
cd $WORKSPACE
