#!/bin/sh -ex

git remote add dce git://github.com/thehajime/net-next-sim.git || echo "ignore"
git fetch dce
git merge dce/sim-ns3-3.10.0-branch

echo "CONFIG_MPTCP=y" >> arch/sim/defconfig
sed "s/CONFIG_SYN_COOKIES=y/\#CONFIG_SYN_COOKIES=y/" arch/sim/defconfig >a
mv a arch/sim/defconfig
make clean ARCH=sim
make defconfig ARCH=sim
make library ARCH=sim COV=yes


cd arch/sim/test
make bake
cd bake
hg pull -u
cd ..
make clean -C buildtop/source/quagga || echo "ignore"
make testbin
cd $WORKSPACE
NS_DCE_MPTCP_ENABLE=1 make test ARCH=sim ADD_PARAM="-r" || echo "====== dce-umip test will probably fails..========="
