#!/bin/sh -ex

git reset
make clean ARCH=lib
make defconfig ARCH=lib
make library ARCH=lib COV=yes

cd arch/lib/test
make bake
cd bake
hg pull -u
cd ..
make clean -C buildtop/source/quagga || echo "ignore"
make testbin
cd $WORKSPACE
make test ARCH=lib ADD_PARAM="-r"
