#!/bin/sh -ex

git reset
make clean ARCH=sim
make defconfig ARCH=sim
make library ARCH=sim COV=yes

cd arch/sim/test
make bake
cd bake
hg pull -u
cd ..
make clean -C buildtop/source/quagga || echo "ignore"
make testbin
cd $WORKSPACE
make test ARCH=sim
