#!/bin/sh -ex

BAKECONF_PARAMS=$1
#echo "$BAKECONF_PARAMS"

git remote add dce git://github.com/direct-code-execution/net-next-sim.git || echo "ignore"
git fetch dce
git merge dce/sim-ns3-3.11.0-branch --no-commit

cat >> arch/sim/defconfig <<END
CONFIG_MPTCP=y
CONFIG_MPTCP_PM_ADVANCED=y
CONFIG_MPTCP_FULLMESH=y
CONFIG_MPTCP_NDIFFPORTS=y
CONFIG_DEFAULT_FULLMESH=y
CONFIG_DEFAULT_MPTCP_PM="fullmesh"

CONFIG_TCP_CONG_COUPLED=y
CONFIG_TCP_CONG_OLIA=y

END

make clean ARCH=sim
make defconfig ARCH=sim
make library ARCH=sim COV=yes

cd arch/sim/test
make bake
cd bake
hg pull -u
cd ..
make clean -C buildtop/source/quagga || echo "ignore"
make testbin BAKECONF_PARAMS="$BAKECONF_PARAMS"
cd $WORKSPACE
make test ARCH=sim ADD_PARAM="-r"
