#!/bin/sh -ex

rm -f lcov_cobertura.py
wget --no-check-certificate https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py
chmod +x lcov_cobertura.py

KERNROOT=`pwd`
cd arch/lib/test/buildtop/source/ns-3-dce/
TESTDIR=./testpy-output/ ./utils/lcov.sh $KERNROOT
cd ../../../../../../
./lcov_cobertura.py arch/lib/test/buildtop/source/ns-3-dce/dce-run.info -o coverage-dce.xml
