#!/bin/sh -ex

cd $WORKSPACE
rm -f lcov_cobertura.py
wget https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py
chmod +x lcov_cobertura.py

cd arch/sim/test/buildtop/source/dce/
./utils/lcov.sh $WORKSPACE
cd $WORKSPACE
./lcov_cobertura.py arch/sim/test/buildtop/source/dce/dce-run.info -o coverage-dce.xml
